### PR TITLE
fix(aws): more permissive netpol for HTTP01

### PR DESCRIPTION
**Pull request by ArchiFleKs**

### CODE REVIEW

**Comment by rguichard** [comment]
is this only needed for aws module ?

**Comment by ArchiFleKs** [comment]
It has already been done [here](https://github.com/particuleio/terraform-kubernetes-addons/commit/9166c4db1dabe7f7ccffb656c4927ca712d20a49) for the other modules, this is an oversight

**Comment by ArchiFleKs** [comment]
@rguichard please merge this one so I can rebase the other PR

**Review by rguichard — APPROVED** [review]
lgtm

**Pull request merged**
