### PR TITLE
feat: update external-dns to latest

### PR DESCRIPTION
**Pull request by ArchiFleKs**

### CODE REVIEW

**Review by tbobm — COMMENTED** [review]
It seems like the chart got updated a couple of hours ago to the 4.7.0 version (see https://github.com/bitnami/charts/commit/f112d71048e4fc3a8330f6b92fdb922fee0091ce), do you want to stick with 4.6.1 ?

**Comment by ArchiFleKs** [comment]
@tbobm I have updated to latest

**Review by tbobm — APPROVED** [review]
lgtm !

**Comment by ArchiFleKs** [comment]
@Mergifyio refresh

**Pull request merged**
