### PR TITLE
feat: Add AWS EFS CSI Driver

### PR DESCRIPTION
**Pull request by mattsimonsen**
I have deployed to AWS via my repo and tested connecting to an EFS mount from a k8s pod.

Please let me know if there's anything else needing adjusting. Feedback is welcome, as I expect to be contributing at least one additional item in the future.

Thanks!
Matt

### CODE REVIEW

**Comment by ArchiFleKs** [comment]
Hi @mattsimonsen thanks for your PR, EFS doesn't need some sort of IAM role for service account ?

**Comment by mattsimonsen** [comment]
I do not believe that the EFS CSI driver needs any special role. It does not provision EFS shares or endpoints, it simply allocates these for K8s node use. So as long as the EFS share has access, which is controlled only by network ACLs, the nodes should have no trouble mounting.

Please let me know if there's anything else that needs attention so this can be included in the project. 

Thanks!
Matt

**Comment by ArchiFleKs** [comment]
@mattsimonsen alright thanks. Could you just fix the CI test that are failing (add the documentation and new variables) :https://github.com/particuleio/terraform-kubernetes-addons/pull/23/checks?check_run_id=2002205989

**Review by ArchiFleKs — APPROVED** [review]

**Comment by mattsimonsen** [comment]
Thanks @ArchiFleKs ! That was fast.

**Comment by ArchiFleKs** [comment]
@mattsimonsen you’re welcome. We are more than happy to see new contributors on this repository ;)

**Pull request merged**
